import type { Metadata } from "next";
import styles from "./styles/layoutStyle.module.scss";
import { Poppins } from "next/font/google";
import "../defaultStyle/default.scss";

export const metadata: Metadata = {
  title: "Test Task Insiders",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[poppins.className, styles.layoutBody].join(" ")}>
        <aside className={styles.layoutBody__aside}></aside>
        <div className="">
          <header>
            <nav></nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
